package com.example.fueledrestaurantapp.model

/**
 * Data models generated by JsonToKotlinClass: https://github.com/wuseal/JsonToKotlinClass
 */

data class FoursquareResponse(
        val meta: Meta,
        val response: Response
)